name: Pull Request Notification

on:
  push:
  pull_request:
  issues:
    types: [opened, closed, reopened, edited, deleted, pinned, unpinned, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]
  issue_comment:
    types: [created, edited, deleted]
  create:
  delete:

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send Github notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,commit,event,action,workflow,ref,url
        custom_payload: |
          {
            "attachments": [
              {
                "color": "${{ job.status }}",
                "title": "${{ github.actor }} ${{ github.event.pull_request.merged == true && 'merged a pull request' || github.event.pull_request && 'opened or updated a pull request' || 'triggered an event' }}",
                "text": ":tada: Event details:\n\n- Repository: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- PR Title: ${{ github.event.pull_request.title }}\n- :globe_with_meridians: Link: ${{ github.event.pull_request.html_url }}"
              }
            ]
          }
