name: Pull Request Notification

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Send Github notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        fields: repo,commit,event,action,workflow,ref,url
        custom_payload: |
          {
            "attachments": [
              {
                "color": "${{ job.status }}",
                "title": "Pull request ${ { github.event.pull_request.state }} by ${ { github.actor }}",
                "text": "#${{ github.event.pull_request.number }} ${ { github.event.pull_request.title }}\n• ${ { github.event.pull_request.body.split('\\n')[0] }}\nLink :\n<${{ github.event.pull_request.html_url }}| ${ { github.event.pull_request.created_at }}>"
              }
            ]
          }
