name: Pull Request Notification

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare PR title
        id: pr-title
        run: echo "PR_TITLE=<${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}>" >> $GITHUB_ENV

      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date --utc --date='${{ github.event.pull_request.created_at }}' +'%B %d, %Y at %I:%M %p')" >> $GITHUB_ENV

      - name: Send Github notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,event,action,workflow,ref,url
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status }}",
                  "title": "Pull request ${{ github.event.pull_request.state == 'open' && 'opened' || github.event.pull_request.merged == true && 'merged' || 'closed' }} by ${{ github.actor }}",
                  "text": ":tada: Event details:\n\n- Repository: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- PR Title: ${ { env.PR_TITLE }}\n- :globe_with_meridians: Link: <${{ github.event.pull_request.html_url }}|Link to PR>\n- Timestamp: ${ { env.CURRENT_DATE }}"
                }
              ]
            }
