name: Pull Request Notification

on:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Fetch checks
#        id: checks
#        env:
#          GH_TOKEN: ${{ github.token }}
#        run: |
#          # Using GitHub CLI or curl to fetch checks
#          # You'll need to use a GitHub Token with read permissions for checks
#          CHECKS=$(gh api /repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/check-runs)
#          echo "CHECKS=${CHECKS}" >> $GITHUB_ENV

      - name: Send Github notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,commit,event,action,workflow,ref,url
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "${{ job.status }}",
                  "title": "Pull request ${{ github.event.pull_request.state == 'open' && 'opened' || github.event.pull_request.merged == true && 'merged' || 'closed' }} by ${{ github.actor }}",
                  "text": ":tada: Event details:\n\n- Repository: ${{ github.repository }}\n- Branch: ${{ github.ref }}\n- Pull Request Title: #${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}\n- :globe_with_meridians: Link: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.created_at }}>\n\nAll checks have passed\n${{ env.CHECKS }}"
                }
              ]
            }
